### ISSUE TITLE
New games won't work

### ISSUE THREAD

**Issue by jacob-creech** [jacob-creech/fog#1]
In the current state of the project, game_averages will not account for new games that come out since we finished our crawling. Due to this, the application will break at runtime, with a key error while looping through game_averages. 

Suggested fixes:
- Drop new games that we do not have in our master game list, as they will be highly skewed 
- Add new game to master list, and give every other list the rating that the current user gives. This would make this game's data negligible. 
- Take the genre of the game, and give a value based on the playtime. This may be only a temporary fix, and may skew data due to unknown game(may have high replayability, or a short simple game).

**Comment by dlacroix1** [comment]
Fixed: we will ignore games which are not present within our data set. This should be a very minuscule number disregarding new releases since we have collected our data.
