### ISSUE TITLE
Currently owned games being recommended

### ISSUE THREAD

**Issue by jacob-creech** [jacob-creech/fog#2]
In the current state, a game that a user already owns, but currently has 0 playtime, will be recommended in our list to the user.

Proposed fix:
- Implement check against currently owned games. Only print if not in currently owned game list.

**Comment by dlacroix1** [comment]
Resolved the issue.
Any game that the user has played for more than zero hours is not added into the final_scores dictionary and therefore will not be recommended to the user.
