### ISSUE TITLE
Game ratings are currently vastly different

### ISSUE THREAD

**Issue by jacob-creech** [jacob-creech/fog#3]
The current recommender will recommend games based on popularity, and does not take into account games that may be good, but played little. 

Eg: Bioshock Infinite, while a good game, may not be played over and over again. A 8 hour game will be skewed heavily against the popular titles such as TF2, CS:GO, which all have hundreds of hours of replay-ability. 

Proposed fix:
Normalize by average amount of hours played per game, then create the ratings system. This will allow for the recommender not to be biased towards popular games, and instead take into account how much each game is played above the average. Will give a more accurate estimate of how "good" or "enjoyable" a game may be.

**Comment by dlacroix1** [comment]
Fixed: The scores are now normalized based on average hours played of a game by all users.
